"""initial

Revision ID: 94b6061dae61
Revises: 
Create Date: 2026-03-29 02:44:33.801478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94b6061dae61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('db_client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redis_client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_name_client'), 'apps', ['name_client'], unique=True)
    op.create_table('usermasterapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermasterapp_email'), 'usermasterapp', ['email'], unique=True)
    op.create_index(op.f('ix_usermasterapp_username'), 'usermasterapp', ['username'], unique=True)
    op.create_table('access_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_app', sa.Integer(), nullable=False),
    sa.Column('access_app', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_app'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_app', sa.Integer(), nullable=False),
    sa.Column('urls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_app'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    op.drop_table('access_app')
    op.drop_index(op.f('ix_usermasterapp_username'), table_name='usermasterapp')
    op.drop_index(op.f('ix_usermasterapp_email'), table_name='usermasterapp')
    op.drop_table('usermasterapp')
    op.drop_index(op.f('ix_apps_name_client'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
