"""new_column_redis

Revision ID: 7701845d7633
Revises: 88fd069cf351
Create Date: 2026-03-26 01:09:31.361425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7701845d7633'
down_revision: Union[str, Sequence[str], None] = '88fd069cf351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('redis_client', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'redis_client')
    # ### end Alembic commands ###
