"""change_names_app_columns

Revision ID: 88fd069cf351
Revises: e1f9f5504d9d
Create Date: 2026-03-25 22:44:26.242388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88fd069cf351'
down_revision: Union[str, Sequence[str], None] = 'e1f9f5504d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('name_client', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('apps', sa.Column('db_client', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_apps_name'), table_name='apps')
    op.create_index(op.f('ix_apps_name_client'), 'apps', ['name_client'], unique=True)
    op.drop_column('apps', 'db')
    op.drop_column('apps', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('apps', sa.Column('db', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_apps_name_client'), table_name='apps')
    op.create_index(op.f('ix_apps_name'), 'apps', ['name'], unique=True)
    op.drop_column('apps', 'db_client')
    op.drop_column('apps', 'name_client')
    # ### end Alembic commands ###
